### ISSUE TITLE
Failed to create a project - tag name expected

### ISSUE THREAD

**Issue by pksol** [TezRomacH/python-package-template#437]
## 🐛 Bug Report

I failed to create a project using the cookie cutter, tried several times, and got the same error:

```
Traceback (most recent call last):
  File "/home/peter/.local/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/peter/.local/lib/python3.8/site-packages/cookiecutter/cli.py", line 140, in main
    cookiecutter(
  File "/home/peter/.local/lib/python3.8/site-packages/cookiecutter/main.py", line 101, in cookiecutter
    result = generate_files(
  File "/home/peter/.local/lib/python3.8/site-packages/cookiecutter/generate.py", line 352, in generate_files
    generate_file(
  File "/home/peter/.local/lib/python3.8/site-packages/cookiecutter/generate.py", line 169, in generate_file
    tmpl = env.get_template(infile_fwd_slashes)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "./pyproject.toml", line 45, in <module>
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 125, in parse_statement
    self.fail('tag name expected', token.lineno)
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: tag name expected
  File "./pyproject.toml", line 45
    {%+ if cookiecutter.create_example_template == 'cli' %}

```

## 🔬 How To Reproduce

1. Run cookiecutter `gh:TezRomacH/python-package-template --checkout v1.1.0`
2. Then select:
3. You've downloaded /home/peter/.cookiecutters/python-package-template before. Is it okay to delete and re-download it? [yes]:  (yes)
4. project_name [python-project]: flac-converter
5. project_description [Awesome `flac-converter` is a Python cli/package created with https://github.com/TezRomacH/python-package-template]: (default)
6. organization [flac-converter]: pksol
7. license: default MIT
8. minimal_python_version: - 3.7
9. github_name [pksol]: (default)
10. email [hello@pksol.com]: kogan.peter@gmail.com
11. version [0.1.0]: (default)
12. line_length [88]: (default)
13. create cli (default)
14. Then the above exception happens

### Environment

* OS: Linux - Ubuntu
* Python version: 3.8.10

## 📈 Expected behavior

The project is created.

**Comment by TezRomacH** [comment]
Hi! I couldn't reproduce the error. What version of cookiecutter do you have?

```bash
~/Documents/aiml 
❯ cookiecutter python-package-template                               
project_name [python-project]: flac-converter
project_description [Awesome `flac-converter` is a Python cli/package created with https://github.com/TezRomacH/python-package-template]: 
organization [flac-converter]: pksol
Select license:
1 - MIT
2 - BSD-3
3 - GNU GPL v3.0
4 - Apache Software License 2.0
Choose from 1, 2, 3, 4 [1]: 
Select minimal_python_version:
1 - 3.7
2 - 3.8
3 - 3.9
Choose from 1, 2, 3 [1]: 
github_name [pksol]: 
email [hello@pksol.com]: kogan.peter@gmail.com
version [0.1.0]: 
line_length [88]: 
Select create_example_template:
1 - cli
2 - none
Choose from 1, 2 [1]: 

Your project flac-converter is created.

1) Now you can start working on it:

    $ cd flac-converter && git init

2) If you don't have Poetry installed run:

    $ make poetry-download

3) Initialize poetry and install pre-commit hooks:

    $ make install
    $ make pre-commit-install

4) Run codestyle:

    $ make codestyle

5) Upload initial code to GitHub:

    $ git add .
    $ git commit -m ":tada: Initial commit"
    $ git branch -M main
    $ git remote add origin https://github.com/pksol/flac-converter.git
    $ git push -u origin main


~/Documents/aiml took 36s 
```
I will post the new version 1.1.1 within an hour. I have only updated the library versions, but I hope it will help and fix something 🤔 

Sorry for the long wait for an answer.

**Comment by TezRomacH** [comment]
Please try to update the cookiecutter and run 
```
cookiecutter gh:TezRomacH/python-package-template --checkout v1.1.1
```

**Comment by pksol** [comment]
I checked my version of cookiecutter and it was already 1.7.3. Then I tried to run the command you sent with v1.1.1 and got the same exception:
```
Traceback (most recent call last):
  File "/home/peter/.local/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/peter/.local/lib/python3.8/site-packages/cookiecutter/cli.py", line 140, in main
    cookiecutter(
  File "/home/peter/.local/lib/python3.8/site-packages/cookiecutter/main.py", line 101, in cookiecutter
    result = generate_files(
  File "/home/peter/.local/lib/python3.8/site-packages/cookiecutter/generate.py", line 352, in generate_files
    generate_file(
  File "/home/peter/.local/lib/python3.8/site-packages/cookiecutter/generate.py", line 169, in generate_file
    tmpl = env.get_template(infile_fwd_slashes)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "./pyproject.toml", line 45, in <module>
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 125, in parse_statement
    self.fail('tag name expected', token.lineno)
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: tag name expected
  File "./pyproject.toml", line 45
    {%+ if cookiecutter.create_example_template == 'cli' %}
```

**Comment by pksol** [comment]
I tried to uninstall and then reinstalled cookie-cutter, got the same result.

**Comment by pksol** [comment]
Solved! It was an issue with a python installation.

I created a new installation and a virtual environment and run it through there and it worked: `python -m cookiecutter  gh:TezRomacH/python-package-template --checkout v1.1.1`

**Comment by TezRomacH** [comment]
I'm glad it ended successfully!
